language: cpp
compiler:
- gcc
before_install:
- echo $LANG
- echo $LC_ALL
- rvm use $RVM_VERSION --install --binary --fuzzy
- gem update --system
- gem install rake
- gem install net-ssh
- gem install net-sftp
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get -qq install automake
- sudo apt-get -qq install g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- gcc --version
- aclocal --version
- openssl aes-256-cbc -K $encrypted_2d08df12a66b_key -iv $encrypted_2d08df12a66b_iv -in scripts/travis-store.key.enc -out scripts/travis-store.key -d
- chmod 0600 scripts/travis-store.key
before_script: rake travis:prepare
script: rake travis:run_build
branches:
  only:
  - master
env:
  matrix:
  - RVM_VERSION=2.0.0 LANG="en_US.UTF-8" 
  global:
  - secure: c2PdYqzmULeCy8v0r/zcICGrzaUp+UNmGtHFmNZkDxdPgcDLcofGho8XeVVUtYmML1aWfrx/rZuDqjzNY/FQGvlw7FgW2vgqiAvrV6cRYDUO8TyGz4GyCcEPulT9lUR+6/PnchtPcDNdRi3UnGD7XKk0lkfaWB3RpPPD9MzXl6k=
  - secure: RtrIzQ46kjHc1mNWdKplGRndBxMSUMnY2i9F/r7Xu4tGZeOUqPp77opRnXHxAWNA2BEO6Ts5D3EAiRFSkqygVmbm8WkBfDpnuBGv0+uQzQXSZCOnfLHjStuoNqnBAEoTa+JIxCYYIz4IcwpPwcdErK3p32BVbL3axMjkpwYsrkM=
os:
- linux
## disable toolchain-staging for now
#before_deploy: rake toolchain:archive
#deploy:
#  - provider: releases
#    api_key:
#      secure: CJkNron+GJzqTp0Wa+5xHW+Gy5XIRCtx2LHlluF+4HTM5Pyu/IymTAHSu3+v+6InWfgt2sb35NcLYM05PPx/6XAkxu5S6WaWbl7dmkp9VD7h1OG8xCjF9/SRRGNF6j9PSsccqZ6MbbDi+k9Ye5VAcJLE1TlRGgFYF4C+6EEdGLE=
#    file: toolchain-*.tar.bz2
#    skip_cleanup: true
#    on:
#      repo: Shirk/Hotarubi
#      condition: "$(git log -1 --pretty='format:%h' scripts/toolchain-meta.yaml scripts/patches) = $(git log -1 --pretty='format:%h')"
