language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - rvm use $RVM_VERSION --install --binary --fuzzy
  - gem update --system
  - gem --version
  - gem install rake
  - rake --version
before_script:
  - rake toolchain:build
script:
  - rake
branches:
  only:
    - master
env:
  - RVM_VERSION=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
