require 'yaml'
require 'rake/clean'
require 'rake/loaders/makefile'

Dir.glob( './scripts/**/*.rake' ).each { |rake_ext| import rake_ext }

# rake defaults
task :default => :kernel

desc "Build hotaru.elf"
task :kernel => 'hotaru.elf' do
  puts "Ready."
end

# collect sources and options files
SOURCES    = FileList.new( 'src/**/*.c', 'src/**/*.cc', 'src/**/*.S' )
SOURCES_64 = FileList.new( SOURCES )
SOURCES_32 = FileList.new
OBJECTS    = SOURCES.ext( '.o' )
DEPENDS    = SOURCES.ext( '.d' )

# split sources into 64bit and 32bit
Dir.glob( 'src/**/options.yaml' ).each do |option_file|
  { :sources_32 => [] }.merge( YAML::load_file( option_file ) )[ :sources_32 ].each do |src|
    SOURCES_32 << SOURCES_64.delete( "#{File.dirname( option_file )}/#{src}" )
  end
end

# file targets for kernel and *.o
file 'hotaru.elf' => [ *OBJECTS, 'Rakefile', 'scripts/link.ld' ] do |t|
  cc_link( OBJECTS, t.name.ext( '.elf64' ) )
  cc_64to32( t.name.ext( '.elf64' ), t.name, :cleanup => false )
end

SOURCES_64.each do |src|
  file src.ext( '.o' ) => [ src, 'Rakefile' ] do |t|
    cc_compile( src, t.name )
  end
end

SOURCES_32.each do |src|
  file src.ext( '.o' ) => [ src, 'Rakefile' ] do |t|
    cc_compile( src, t.name, :use32 => true )
  end
end

unless Rake.application.top_level_tasks.join( ' ' ) =~ /(toolchain:.*|clean)/
  # include autogenerated depends
  file '.depends.mf' => DEPENDS do |t|
    puts "GEN      #{t.name}"
    sh "cat #{t.prerequisites.join( ' ' )} > #{t.name}", :verbose => false
  end

  import '.depends.mf'
end

CLEAN.include( OBJECTS )
CLEAN.include( DEPENDS )
CLEAN.include( '**/*.o32' )
CLEAN.include( '**/*.o64' )
CLEAN.include( '**/*.elf32' )
CLEAN.include( '**/*.elf64' )
CLEAN.include( '.depends.mf' )

CLOBBER.include( 'hotaru.elf' )
CLOBBER.include( 'Symbols.map' )
